
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."item" (
    "ItemID" bigint NOT NULL,
    "Name" "text" NOT NULL,
    "Price" numeric
);

ALTER TABLE "public"."item" OWNER TO "postgres";

ALTER TABLE "public"."item" ALTER COLUMN "ItemID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."item_ItemID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."receipt" (
    "ReceiptID" bigint NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "TotalAmount" numeric,
    "StoreID" bigint NOT NULL,
    "UserID" bigint
);

ALTER TABLE "public"."receipt" OWNER TO "postgres";

ALTER TABLE "public"."receipt" ALTER COLUMN "ReceiptID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."receipt_ReceiptID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."receipt_item" (
    "ReceiptID" bigint NOT NULL,
    "ItemID" bigint NOT NULL,
    "Quantity" bigint,
    "Subtotal" numeric
);

ALTER TABLE "public"."receipt_item" OWNER TO "postgres";

ALTER TABLE "public"."receipt_item" ALTER COLUMN "ReceiptID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."receipt_item_ReceiptID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."store" (
    "StoreID" bigint NOT NULL,
    "Name" "text" NOT NULL
);

ALTER TABLE "public"."store" OWNER TO "postgres";

ALTER TABLE "public"."store" ALTER COLUMN "StoreID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."store_StoreID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."user" (
    "UserID" bigint NOT NULL,
    "UserName" character varying,
    "Email" character varying,
    "CreatedAt" "date"
);

ALTER TABLE "public"."user" OWNER TO "postgres";

ALTER TABLE "public"."user" ALTER COLUMN "UserID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_UserID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."item"
    ADD CONSTRAINT "item_pkey" PRIMARY KEY ("ItemID");

ALTER TABLE ONLY "public"."receipt"
    ADD CONSTRAINT "receipt_StoreID_key" UNIQUE ("StoreID");

ALTER TABLE ONLY "public"."receipt_item"
    ADD CONSTRAINT "receipt_item_pkey" PRIMARY KEY ("ReceiptID", "ItemID");

ALTER TABLE ONLY "public"."receipt"
    ADD CONSTRAINT "receipt_pkey" PRIMARY KEY ("ReceiptID");

ALTER TABLE ONLY "public"."store"
    ADD CONSTRAINT "store_StoreID_key" UNIQUE ("StoreID");

ALTER TABLE ONLY "public"."store"
    ADD CONSTRAINT "store_pkey" PRIMARY KEY ("StoreID");

ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY ("UserID");

ALTER TABLE ONLY "public"."receipt"
    ADD CONSTRAINT "receipt_StoreID_fkey" FOREIGN KEY ("StoreID") REFERENCES "public"."store"("StoreID");

ALTER TABLE ONLY "public"."receipt"
    ADD CONSTRAINT "receipt_UserID_fkey" FOREIGN KEY ("UserID") REFERENCES "public"."user"("UserID");

ALTER TABLE ONLY "public"."receipt_item"
    ADD CONSTRAINT "receipt_item_ItemID_fkey" FOREIGN KEY ("ItemID") REFERENCES "public"."item"("ItemID");

ALTER TABLE ONLY "public"."receipt_item"
    ADD CONSTRAINT "receipt_item_ReceiptID_fkey" FOREIGN KEY ("ReceiptID") REFERENCES "public"."receipt"("ReceiptID");

ALTER TABLE "public"."item" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."receipt" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."receipt_item" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."store" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."item" TO "anon";
GRANT ALL ON TABLE "public"."item" TO "authenticated";
GRANT ALL ON TABLE "public"."item" TO "service_role";

GRANT ALL ON SEQUENCE "public"."item_ItemID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."item_ItemID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."item_ItemID_seq" TO "service_role";

GRANT ALL ON TABLE "public"."receipt" TO "anon";
GRANT ALL ON TABLE "public"."receipt" TO "authenticated";
GRANT ALL ON TABLE "public"."receipt" TO "service_role";

GRANT ALL ON SEQUENCE "public"."receipt_ReceiptID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."receipt_ReceiptID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."receipt_ReceiptID_seq" TO "service_role";

GRANT ALL ON TABLE "public"."receipt_item" TO "anon";
GRANT ALL ON TABLE "public"."receipt_item" TO "authenticated";
GRANT ALL ON TABLE "public"."receipt_item" TO "service_role";

GRANT ALL ON SEQUENCE "public"."receipt_item_ReceiptID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."receipt_item_ReceiptID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."receipt_item_ReceiptID_seq" TO "service_role";

GRANT ALL ON TABLE "public"."store" TO "anon";
GRANT ALL ON TABLE "public"."store" TO "authenticated";
GRANT ALL ON TABLE "public"."store" TO "service_role";

GRANT ALL ON SEQUENCE "public"."store_StoreID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."store_StoreID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."store_StoreID_seq" TO "service_role";

GRANT ALL ON TABLE "public"."user" TO "anon";
GRANT ALL ON TABLE "public"."user" TO "authenticated";
GRANT ALL ON TABLE "public"."user" TO "service_role";

GRANT ALL ON SEQUENCE "public"."user_UserID_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_UserID_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_UserID_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
